# Generated by Django 5.0.6 on 2024-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reporting_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='table_id',
            field=models.IntegerField(),
        ),
    ]
