# Generated by Django 5.0.6 on 2024-05-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_reporting_table_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporting',
            old_name='table_id',
            new_name='table_ID',
        ),
    ]
