# Generated by Django 5.0.6 on 2024-05-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_table_id_reporting_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
