# Generated by Django 5.0.6 on 2024-05-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order',
        ),
    ]
