# Generated by Django 5.0.6 on 2024-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order',
            field=models.CharField(default='it will be added automatically', max_length=1000),
        ),
    ]
