# Generated by Django 5.0.6 on 2024-05-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_booking_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
