# Generated by Django 5.0.6 on 2024-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_booking_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bill',
            field=models.FloatField(default=0),
        ),
    ]
