# Generated by Django 5.0.6 on 2024-05-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cancel',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
