# Generated by Django 5.0.6 on 2025-06-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='bot_response',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user_input',
            field=models.CharField(max_length=1000),
        ),
    ]
