# Generated by Django 5.0.6 on 2025-06-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_chatbot_bot_response_alter_chatbot_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='user_input',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
