# Generated by Django 5.0.6 on 2025-06-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_uploadedimage_user_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='user_input',
        ),
    ]
